import Foundation
@testable import PeachEngine

/// The TypeScript engine's `dayIndex` answers, generated by
/// `tools/generate-oracle.mjs`.
///
/// `Codable` is Swift's built-in JSON mapping: conforming a struct to it
/// generates the decoder from the stored properties, so there is no
/// hand-written parsing and a shape mismatch is a decode error rather than an
/// `undefined` surfacing at some later line. TypeScript's `JSON.parse` returns
/// `any`.
struct OracleFixture: Codable {
    struct DayIndexCase: Codable {
        let zone: String
        let instant: String
        let dayIndex: Int
    }
    struct Epoch: Codable {
        let year: Int
        let month: Int
        let day: Int
    }

    let epoch: Epoch
    let dayIndexCases: [DayIndexCase]

    var epochDate: EpochDate {
        EpochDate(year: epoch.year, month: epoch.month, day: epoch.day)
    }

    static let shared: OracleFixture = {
        let url = repositoryRoot
            .appendingPathComponent("Fixtures")
            .appendingPathComponent("oracle.json")
        // Force-unwrapping in a test helper is deliberate: a missing or
        // malformed oracle should fail loudly and immediately, not degrade into
        // a suite that silently checks nothing.
        let data = try! Data(contentsOf: url)
        return try! JSONDecoder().decode(OracleFixture.self, from: data)
    }()
}
