// Generates Fixtures/oracle.json: the TypeScript engine's dayIndex answers, so
// the Swift port can be checked against them rather than against a reading of
// the source.
//
// Run: node tools/generate-oracle.mjs
//
// SCOPE. This covers dayIndex ONLY. The plan's contingency was applied: the
// PRNG paths (seededPermutation, cycleOrder, seedForCycle) are covered instead
// by Node-verified values hardcoded directly in the Swift tests. dayIndex keeps
// a generated fixture because it is where cross-language divergence genuinely
// lives — JS Date reads local components from the process TZ, Swift's Date has
// no local accessors at all — and it is the only part with no hardcoded
// coverage. See docs/REPORT.md.
//
// dayIndex below is copied verbatim from the web repo at commit 475edfc
// (src/engine/daily.ts). Copied, not imported: this repo does not depend on
// that one.
import { writeFileSync, mkdirSync } from 'node:fs';

function dayIndex(date, epoch) {
  const today = Date.UTC(date.getFullYear(), date.getMonth(), date.getDate());
  const start = Date.UTC(epoch.year, epoch.month - 1, epoch.day);
  return Math.floor((today - start) / 86_400_000);
}

const EPOCH = { year: 2026, month: 1, day: 1 };

// dayIndex reads a JS Date's LOCAL components, so each case must be generated
// with process.env.TZ set to that case's zone. Node reads TZ once at startup,
// so the script re-execs itself per zone rather than looping.
const ZONE_CASES = {
  'America/Los_Angeles': [
    // Around DST forward: 2026-03-08 02:00 PST -> 03:00 PDT (a 23-hour day).
    '2026-03-07T23:59:00-08:00', '2026-03-08T00:00:00-08:00',
    '2026-03-08T01:59:00-08:00', '2026-03-08T03:00:00-07:00',
    '2026-03-08T23:59:00-07:00',
    // Around DST back: 2026-11-01 02:00 PDT -> 01:00 PST (01:30 happens twice).
    '2026-11-01T00:30:00-07:00', '2026-11-01T01:30:00-08:00',
    '2026-11-01T23:59:00-08:00',
    // The epoch day itself, and the daily epoch.
    '2026-01-01T00:00:00-08:00', '2026-06-23T12:00:00-07:00',
  ],
  // Far from UTC in both directions, plus midnight-transition zones and a
  // half-hour and 45-minute offset, because those are where naive day
  // arithmetic breaks.
  'Pacific/Kiritimati': ['2026-09-05T12:00:00Z', '2026-09-05T10:30:00Z'],
  'Pacific/Apia': ['2026-09-05T12:00:00Z'],
  'Asia/Kolkata': ['2026-09-05T12:00:00Z', '2026-09-05T18:35:00Z'],
  'Pacific/Chatham': ['2026-09-05T11:00:00Z'],
  'America/Santiago': ['2026-09-06T02:30:00Z', '2026-09-06T04:30:00Z'],
  'Australia/Lord_Howe': ['2026-04-05T15:30:00Z'],
  'UTC': ['2026-01-01T00:00:00Z', '2026-01-01T23:59:59Z', '2025-12-31T23:59:59Z'],
};

function runZone(zone) {
  return ZONE_CASES[zone].map((iso) => ({
    zone,
    instant: iso,
    dayIndex: dayIndex(new Date(iso), EPOCH),
  }));
}

if (process.argv[2] === '--zone') {
  process.stdout.write(JSON.stringify(runZone(process.argv[3])));
} else {
  const { execFileSync } = await import('node:child_process');
  const dayIndexCases = Object.keys(ZONE_CASES).flatMap((zone) =>
    JSON.parse(
      execFileSync(process.execPath, [process.argv[1], '--zone', zone], {
        env: { ...process.env, TZ: zone },
        encoding: 'utf8',
      }),
    ),
  );

  mkdirSync('Fixtures', { recursive: true });
  writeFileSync(
    'Fixtures/oracle.json',
    JSON.stringify(
      {
        note: 'Generated by tools/generate-oracle.mjs from the TypeScript engine at web commit 475edfc. dayIndex only — see the header comment. Do not hand-edit.',
        epoch: EPOCH,
        dayIndexCases,
      },
      null,
      2,
    ) + '\n',
  );
  console.log(`wrote Fixtures/oracle.json: ${dayIndexCases.length} dayIndex cases across ${Object.keys(ZONE_CASES).length} zones`);
}
